name: Build and Release Agents.fun UI

on:
  push:
    tags:
      - 'v*-agentsfun'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-app.yml
    permissions:
      contents: write
    with:
      app-name: agentsfun-ui
